### ISSUE TITLE
deletePlanet Bug

### ISSUE THREAD

**Issue by sciuridae0603** [OKTW-Network/Galaxy#191]
如果玩家A在星球中登出
接下來刪除星球後
玩家A在登入時會重新產生地圖
![image](https://user-images.githubusercontent.com/13612494/44480199-4099b600-a675-11e8-9ee6-1c3ba0ee79e1.png)

**Comment by jimchen5209** [comment]
你應該只有刪到 world 資料夾的世界
所以那個世界還在Sponge的註冊資料裡面
如果是從插件刪應該會連世界的註冊都刪掉
你要直接刪的話你要連 `config/sponge/worlds/Minecraft/<世界類型>/<世界名稱>` 這個資料夾也刪掉
喔對了刪掉之後記得重開
如果玩家在沒有註冊過的世界登出他會被強制踢回主世界
