### ISSUE TITLE
Rewrite Recipes

### ISSUE THREAD

**Issue by mmis1000** [OKTW-Network/Galaxy#206]
Tracking issue for recipes (and the star dust count it required)

 - [x] Materials
 - [ ] Upgrades
 - [ ] Guns
 - [ ] Sowrds
 - [x] Teleporters
   - [x] Teleporter
   - [x] Advanced Teleporter
   - [x] Teleporter Frame

**Comment by james58899** [comment]
Drop 1.12.2
